# Make sure to check the documentation at https://goreleaser.com
version: 2
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - binary: software-catalog-api
    env:
      - CGO_ENABLED=0
    ldflags:
     - -s -w
    goos:
      - linux
archives:
  - formats:
      - tar.gz
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
dockers:
 -
   dockerfile: Dockerfile.goreleaser
   image_templates:
     - "ghcr.io/italia/developers-italia-api:{{ .Tag }}"
     - "ghcr.io/italia/developers-italia-api:latest"
