#
# This is the Docker image that gets published to GitHub.
#
# Goreleaser takes care of building the binary.
#
FROM alpine:3.24@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b

COPY software-catalog-api /usr/local/bin/software-catalog-api
RUN ln -s /usr/local/bin/software-catalog-api /usr/local/bin/developers-italia-api

ENTRYPOINT ["/usr/local/bin/software-catalog-api"]
