#
# This is the Docker image that gets published to GitHub.
#
# Goreleaser takes care of building the binary.
#
FROM alpine:3

COPY software-catalog-api /usr/local/bin/software-catalog-api
RUN ln -s /usr/local/bin/software-catalog-api /usr/local/bin/developers-italia-api

ENTRYPOINT ["/usr/local/bin/software-catalog-api"]
