apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "developers-italia-api.fullname" . }}-migrate
  labels:
    {{- include "developers-italia-api.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 0
  activeDeadlineSeconds: 300
  template:
    metadata:
      labels:
        {{- include "developers-italia-api.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "developers-italia-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: migrate
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["developers-italia-api", "migrate"]
          env:
            - name: DATABASE_DSN
              valueFrom:
                secretKeyRef:
                  name: {{ default (include "developers-italia-api.fullname" .) .Values.useExistingSecret }}
                  key: databaseDSN
            {{- if .Values.migrationBaseline }}
            - name: MIGRATION_BASELINE
              value: {{ .Values.migrationBaseline | quote }}
            {{- end }}
