{{- if not .Values.useExistingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "developers-italia-api.fullname" . }}
  labels:
    {{- include "developers-italia-api.labels" . | nindent 4 }}
type: Opaque
data:
  databaseDSN: {{ .Values.databaseDSN | b64enc }}
  pasetoKey: {{ .Values.pasetoKey | b64enc }}
{{- end }}
