{{- if not .Values.useExistingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "developers-italia-api.fullname" . }}
  labels:
    {{- include "developers-italia-api.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.postgres }}
  databaseDSN: {{ printf "host=%s user=%s password=%s dbname=%s port=%v" .host .user .password .database .port | b64enc }}
  {{- end }}
  pasetoKey: {{ .Values.pasetoKey | b64enc }}
{{- end }}
