on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24.x
      - uses: golangci/golangci-lint-action@v7
        with:
          version: v2.4.0
          args: --timeout 3m --verbose
