on:
  push:
    branch: main
  pull_request:
    branch: main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
      - uses: golangci/golangci-lint-action@v3
