# Push the staging Docker image (ghcr.italia/developers-italia-api:main)
# on updates to main.

on:
  push:
    branches: [main]
    paths:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
      - 'Dockerfile*'
      - '.goreleaser*.yaml'

permissions:
  # To push Docker images to GitHub
  packages: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version: 1.25.x
          cache: false
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
          # All history, required for goreleaser
          fetch-depth: 0
      - # FIXME: goreleaser should already take care of the login
        # (see https://github.com/goreleaser/goreleaser/blame/02a3486d4ba59505113a57b438ae567351ed3dab/scripts/entrypoint.sh#L17)
        # but it doesn't work for some reason.
        run: echo "$GITHUB_TOKEN" | docker login ghcr.io -u docker --password-stdin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - # Tag with a temporary valid semantic version. This is required by goreleaser.
        run: git tag v0-main-$(git rev-parse --short HEAD)

      - uses: goreleaser/goreleaser-action@5daf1e915a5f0af01ddbcd89a43b8061ff4f1a89 # v7
        with:
          version: v2.15.2
          args: release --config .goreleaser.staging.yaml
