on:
  push:
    tags:
      - helm/*

permissions: {}

jobs:
  release_chart:
    runs-on: ubuntu-22.04
    permissions:
      # To check out the repository
      contents: read
      # To push the chart to GitHub Container Registry
      packages: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Get version
        id: get_version
        run: echo "::set-output name=version::${GITHUB_REF_NAME#helm/}"
      - name: Push chart to GitHub Container Registry
        uses: appany/helm-oci-chart-releaser@d94988c92bed2e09c6113981f15f8bb495d10943 # v0.5.0
        with:
          name: developers-italia-api
          repository: ${{ github.repository }}/charts
          tag: ${{ steps.get_version.outputs.version }}
          registry: ghcr.io
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
