on:
  push:
    branches: [main]
    paths:
      - '*.oas.yaml'
  pull_request:
    branches: [main]
    paths:
      - '*.oas.yaml'

permissions: {}

jobs:
  spectral:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - run: curl --fail -L https://github.com/italia/api-oas-checker-rules/releases/download/1.1/spectral-full.yml > .spectral.yml

      # Get the custom function required by spectral-full
      - run: mkdir functions
      - run: curl --fail -L https://raw.githubusercontent.com/italia/api-oas-checker/f6f4e6e360b2ce9816dcca29396571dda1c6027d/security/functions/checkSecurity.js > functions/checkSecurity.js

      - uses: bfabio/spectral-action@5af95a6a2985901bd5e689c663b4f93c660f0d2c
        with:
          file_glob: software-catalog-api.oas.yaml
          spectral_ruleset: .spectral.yml
          repo_token: ${{ secrets.GITHUB_TOKEN }}
