on:
  push:
    branches: [main]
    paths:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
  pull_request:
    branches: [main]
    paths:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'

jobs:
  tests-postgresql:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: 1.25.x
      - uses: ariga/setup-atlas@v0
        with:
          version: v1.1.0
      - name: Apply migrations
        run: atlas migrate apply --url "postgres://postgres:postgres@localhost:5432/test?sslmode=disable" --dir "file://internal/database/migrations" --tx-mode file
      - run: go test -race ./...
        env:
          DATABASE_DSN: "postgres://postgres:postgres@localhost:5432/test?sslmode=disable"
